### ISSUE TITLE
Repository Name

### ISSUE THREAD

**Issue by atishelmanch** [CMS-ECAL-Trigger-Group/ETTAnalyzer#3]
I think the repository named should be changed, as in general this repository doesn't need to be specifically for ECAL Double Weights tests, but rather any ETT tests which use our python config files and ETTAnalyzer.

Maybe we can name it something more general like "ETTAnalyzer" or "ETT_Tools" as this is the only main directory in the repository anyway. 

@ramankhurana @valsdav What do you think?

**Comment by ramankhurana** [comment]
1. I agree with this, We started in this direction (double weights) but since the code has evolved a bit and can be used for multiple generic studies we can give a more suitable name. But note that we might have to change in all branches or at least a few which we know we will be using. Otherwise the compilation would break. sed might be useful to do bulk replace. 

2. But at the same time the config in the 11_3_X is more suitable for double weights, although can be used for Run 2 config with command-line (I believe) but not the clean option to do it. 

3.  I would therefore suggest to either create a new repository with new name and decouple the code mainly in terms of double weight config and rest remains same + new development goes int he new repo unless needed for double weights [this will avoid any possible error/bug we might create in renaming etc] OR option 1 above (I can try to rename if we all agree that we just need a plain rename). Not sure which one would be best, any opinion.

**Comment by atishelmanch** [comment]
Hey @ramankhurana - responding to your points:

> But note that we might have to change in all branches or at least a few which we know we will be using. Otherwise the compilation would break.

What would need to be changed to avoid compilation errors? 

> But at the same time the config in the 11_3_X is more suitable for double weights

To me I think it's fine to have separate configuration files for different ETT studies within the same repository. We can have different folders to separate them if we'd like. 

3) In my opinion we can keep everything in one repository and perhaps separate studies by folders or simply by configuration files.

**Comment by atishelmanch** [comment]
Any thoughts on this so that we can close the issue? :) 

Anyone against me just changing the repo name to ETTAnalyzer and checking that the build works from scratch? 

-Abe

**Comment by valsdav** [comment]
agreed

**Comment by atishelmanch** [comment]
Name changed.
